
service: chat
# app and org for use with dashboard.serverless.com
app: chatscrum-app
org: adesanyajoshua

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
  stage: dev



functions:
  connectionHandler:
    handler: handler.connectionHandler
    events:
    - websocket:
        route: $connect
    - websocket:
        route: $disconnect
  defaultHandler:
    handler: handler.defaultHandler
    events:
    - websocket:
        route: $default
  sendMessageHandler:
    handler: handler.sendMessageHandler
    timeout: 10
    events:
      - websocket:
          route: message
  sendHandler:
    handler: handler.sendHandler
    events:
      - websocket:
          route: send

          