
service: chat
# app and org for use with dashboard.serverless.com
app: chatscrum-app
org: adesanyajoshua

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
  stage: dev
  vpc:
    securityGroudIds:
      - sg-0664956cfa7332d1a
    subnetIds:
      - subnet-2158ad7c
      - subnet-4702050c
      - subnet-a5137f8e
      - subnet-cedcc6b7


functions:
  connectionHandler:
    handler: handler.connectionHandler
    events:
    - websocket:
        route: $connect
    - websocket:
        route: $disconnect
  defaultHandler:
    handler: handler.defaultHandler
    events:
    - websocket:
        route: $default
  sendMessageHandler:
    handler: handler.sendMessageHandler
    events:
      - websocket:
          route: message
  initHandler:
    handler: handler.initHandler
    events:
      - websocket:
          route: init

resources:
  Resources:
    LambdaSecurityGroup:
      Type: "AWS::EC2::SecurityGroup"
      Properties:
        GroupName: lj_sec_group
        GroupDescription: Allow all outbound traffic, no inbound
        SecurityGroupIngress:
          - IpProtocol: -1
            CidrIp: 127.0.0.1/32
        VpcId:
          vpc-581e9720
          